"""HTTP views for the simple demo UI."""
from __future__ import annotations

from flask import Blueprint, render_template

from .extensions import db
from .models import Family

views = Blueprint("views", __name__)


@views.route("/")
def index():
    family = Family.query.order_by(Family.created_at).first()
    if not family:
        family = Family(name="Demo Family", description="Autogenerated for the UI")
        db.session.add(family)
        db.session.commit()
    return render_template("index.html", family=family)

